name: Build avahisync

on: [push]

env:
  IMAGE_NAME: ghcr.io/sebbegg/avahisync
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build it

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          set -e

          env | sort

          BUILD_DATE=$(date --rfc-3339=seconds -u | tr " " T)

          docker build . \
          --label "build.build-no=$GITHUB_RUN_NUMBER" \
          --label "build.build-git-hash=$GITHUB_SHA" \
          --label "build.date=$BUILD_DATE" \
          --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          set -e 
          echo "Pushing"
          # docker push $GHTAG
